name: BuildAndDeploy
on: 
  push:
      branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-image:
    runs-on: ubuntu-latest

    outputs:
      IMAGE_TO_DEPLOY: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Generate Docker tags based on the following attributes
          tags: |
            type=sha
          labels: |
            maintainer=boogie@slac.stanford.edu

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64/v8
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  update-test-deployment:
        runs-on: ubuntu-latest
        environment: test
        needs: create-image
        outputs:
            commit_hash: ${{ steps.commit-and-push.outputs.commit_long_sha }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
            - run: |
                echo "Configure test deploy with image ${{needs.create-image.outputs.IMAGE_TO_DEPLOY}}"
                tools/set-image-name.sh ${{needs.create-image.outputs.IMAGE_TO_DEPLOY}} test/deployment.yaml
                
                cat test/deployment.yaml
            - name: Commit and Push Changes
              id: commit-and-push
              run: |
                echo "Commit test deploy with image $DEPLOY_IMAGE" 
                git add test
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git commit -m "Update test deployment ot uses the image '$DEPLOY_IMAGE'"
                git push
                echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  update-production-deployment:
        runs-on: ubuntu-latest
        environment: production
        needs: 
            - update-test-deployment
            - create-image
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
              with:
                ref: main
            - run: |
                echo "Configure production deploy with image ${{needs.create-image.outputs.IMAGE_TO_DEPLOY}}"
                tools/set-image-name.sh ${{needs.create-image.outputs.IMAGE_TO_DEPLOY}} production/deployment.yaml
                cat test/deployment.yaml
                cat production/deployment.yaml
            - name: Commit and Push Changes
              run: |
                  echo "Commit production deploy with image $DEPLOY_IMAGE" 
                  git add production
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git commit -m "Update production deployment ot uses the image '$DEPLOY_IMAGE'"
                  git push
                  echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT